[global]
project_id = "banc-digital-fictici"
rest_url = "http://localhost:8000/rest/v1"
graphql_url = "http://localhost:8000/graphql/v1"
storage_url = "http://localhost:8000/storage/v1"
database_url = "postgresql://postgres:insecure_password_123@localhost:5432/postgres"

[auth]
site_url = "http://localhost:3000"
jwt_secret = "weak_jwt_secret_change_me"
jwt_expiry = 3600
enable_signup = true

[api]
port = 8000
scheme = "http"
host = "0.0.0.0"

[db]
port = 5432
host = "0.0.0.0"
name = "postgres"
password = "insecure_password_123"

[storage]
file_size_limit = 52428800
storage_backend = "local"
file_path = "/var/lib/storage"